### ISSUE TITLE
just, not work

### ISSUE THREAD

**Issue by DaffyDuke** [nethenic/getlegos#1]
Hello,
Perhaps my version of php is not supported yet ?
I got this error : 
```php
getlegos git:(master)  php getlegos.php 8939             
8939PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /tmp/getlegos/getlegos.php:18
Stack trace:
#0 /tmp/getlegos/getlegos.php(36): url2json('https://www.leg...')
#1 /tmp/getlegos/getlegos.php(106): recupInfos('8939')
#2 /tmp/getlegos/getlegos.php(115): moulinette('8939')
#3 {main}
  thrown in /tmp/getlegos/getlegos.php on line 18

```
If it should help, url in code is  https://www.lego.com//service/biservice/search\?fromIndex\=0\&locale\=fr-FR\&onlyAlternatives\=false\&prefixText\= but it looks like real one should be something like  https://www.lego.com/fr-fr/service/buildinginstructions/search\#\?search\&text\=8939%2520Lesovikk%2520Bionicle

If it should helps : 
```
getlegos git:(master)  php -v
PHP 7.1.11-0ubuntu0.17.10.1 (cli) (built: Nov  1 2017 16:30:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11-0ubuntu0.17.10.1, Copyright (c) 1999-2017, by Zend Technologies

```

**Comment by nicolaswurtz** [comment]
Hi !
You're missing "php-curl" extension and you need to install it.
If you are using debian/ubuntu, it's very easy : 
`apt install php-curl`
And then, restart the web server, it should works fine !

**Comment by DaffyDuke** [comment]
Hi, yep, thank you, it worked fine, a quick update to INSTALL.md ? :-)
